(function () {
  'use strict';
  const KEY = 'ajh_intake_v1';
  const STEPS = ['signal', 'slice', 'proof'];
  const $ = (id) => document.getElementById(id);
  const state = { title: '', owner: 'AJH', signal: '', slice: '', proof: '', checks: {}, history: [], views: 0, started: 0 };
  function load() { try { Object.assign(state, JSON.parse(localStorage.getItem(KEY) || '{}')); } catch (_) {} if (!state.checks || typeof state.checks !== 'object') state.checks = {}; if (!Array.isArray(state.history)) state.history = []; }
  function save() { try { localStorage.setItem(KEY, JSON.stringify(state)); } catch (_) {} }
  function complete() { return STEPS.filter((step) => state.checks[step]).length; }
  function escapeHTML(value) { return String(value || '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char])); }
  function summary() { return `AJH Build Intake — ${state.title || 'Untitled slice'}\nOwner: ${state.owner || 'AJH'}\nSignal: ${state.signal || 'Not recorded'}\nSlice: ${state.slice || 'Not recorded'}\nProof: ${state.proof || 'Not recorded'}\nChecks: ${complete()}/3`; }
  function renderHistory() { const list = $('intake-history-list'); if (!list) return; list.innerHTML = state.history.length ? state.history.slice(0, 8).map((item) => `<div class="intake-history-item"><strong>${escapeHTML(item.title)}</strong><span>${escapeHTML(item.owner)} · ${escapeHTML(item.date)}</span><p>${escapeHTML(item.slice || item.proof || 'Slice started.')}</p></div>`).join('') : '<p class="intake-empty">No slices started yet. Define one small move and make its proof visible.</p>'; }
  function render() {
    [['title', 'title'], ['owner', 'owner'], ['signal', 'signal'], ['slice', 'slice'], ['proof', 'proof']].forEach(([field, id]) => { const el = $('intake-' + id); if (el && document.activeElement !== el) el.value = state[field] || ''; });
    document.querySelectorAll('[data-intake-step]').forEach((input) => { input.checked = Boolean(state.checks[input.dataset.intakeStep]); input.closest('.intake-check')?.classList.toggle('is-complete', input.checked); });
    const count = complete(); const ready = count === 3 && state.title.trim();
    $('intake-progress').textContent = `${count}/3`; $('intake-progress-bar').style.width = `${count * 33.333}%`; $('intake-count').textContent = `${count} of 3 checks complete`; $('intake-started').textContent = `${state.started} started`; $('intake-views').textContent = `${state.views} opened`;
    $('intake-status').textContent = ready ? 'Ready to build' : count ? 'Slice taking shape' : 'Waiting for a slice'; $('intake-message').textContent = ready ? 'The next build has a narrow target and a concrete way to know it worked.' : `${3 - count} check${3 - count === 1 ? '' : 's'} left before today has a clean first move.`; $('intake-status-pill').textContent = ready ? 'Ready' : 'Local draft'; $('intake-status-card').classList.toggle('is-complete', Boolean(ready)); renderHistory();
  }
  function update(field, value) { state[field] = value; save(); render(); }
  function importLanding() { const data = window.ajhLanding?.state?.(); const arrival = data?.history?.[0]; const lighthouse = window.ajhLighthouse?.state?.(); if (arrival) { state.title = `Follow up: ${arrival.title}`; state.owner = arrival.owner || 'AJH'; state.signal = arrival.signal || arrival.handoff || 'Imported from Build Landing'; state.slice = `Make the smallest useful follow-up after ${arrival.title}.`; state.proof = 'Run the local quality pass and confirm the new slice keeps the arrival handoff intact.'; } else if (lighthouse?.report?.length) { state.title = 'Repair the first quality warning'; state.signal = `Lighthouse score ${lighthouse.score ?? 'ready'} · start from the first concrete warning`; state.slice = 'Fix one warning without expanding the scope.'; state.proof = 'Run Build Lighthouse again and compare the local score.'; } else { state.signal = 'No prior arrival found; begin with a fresh local read of the page.'; state.slice = 'Choose one small improvement visible to a visitor.'; state.proof = 'Check the changed interaction in a local preview.'; } state.checks = { signal: Boolean(state.signal), slice: Boolean(state.slice), proof: Boolean(state.proof) }; save(); render(); open(); }
  function reset() { Object.assign(state, { title: '', owner: 'AJH', signal: '', slice: '', proof: '', checks: {} }); save(); render(); }
  function start() { if (complete() !== 3 || !state.title.trim()) { $('intake-message').textContent = 'Add a slice title and complete all three checks before starting.'; $('intake-title').focus(); return; } const item = { title: state.title.trim(), owner: state.owner.trim() || 'AJH', signal: state.signal.trim(), slice: state.slice.trim(), proof: state.proof.trim(), date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) }; state.history = [item, ...state.history.filter((entry) => entry.title !== item.title)].slice(0, 8); state.started += 1; state.checks = {}; state.title = ''; state.signal = ''; state.slice = ''; state.proof = ''; save(); render(); $('intake-status').textContent = 'Slice started'; $('intake-message').textContent = 'The move is recorded locally. Build it, then return with proof.'; }
  function copy() { navigator.clipboard?.writeText(summary()).then(() => { $('intake-copy').innerHTML = '<i class="fas fa-check"></i> Copied'; setTimeout(() => { $('intake-copy').innerHTML = '<i class="fas fa-share-nodes"></i> Copy intake'; }, 1400); }); }
  function exportJSON() { const url = URL.createObjectURL(new Blob([JSON.stringify({ ...state, exportedAt: new Date().toISOString() }, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `ajh-build-intake-${new Date().toISOString().slice(0, 10)}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function open() { $('intake')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); state.views += 1; save(); render(); }
  function boot() { load(); [['title', 'title'], ['owner', 'owner'], ['signal', 'signal'], ['slice', 'slice'], ['proof', 'proof']].forEach(([field, id]) => $('intake-' + id)?.addEventListener('input', (event) => update(field, event.target.value))); document.querySelectorAll('[data-intake-step]').forEach((input) => input.addEventListener('change', (event) => { state.checks[event.target.dataset.intakeStep] = event.target.checked; save(); render(); })); $('intake-import')?.addEventListener('click', importLanding); $('intake-reset')?.addEventListener('click', reset); $('intake-copy')?.addEventListener('click', copy); $('intake-export')?.addEventListener('click', exportJSON); $('intake-start')?.addEventListener('click', start); $('intake-hero-btn')?.addEventListener('click', open); document.addEventListener('keydown', (event) => { if (event.target.matches('input, textarea, select, button, a')) return; if (event.shiftKey && event.key.toLowerCase() === 'i') open(); }); window.ajhIntake = { open, importLanding, start, copy, exportJSON, state: () => ({ ...state, checks: { ...state.checks }, history: [...state.history] }) }; render(); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot();
})();