(function () {
  'use strict';
  const KEY = 'ajh_passport_v1';
  const STEPS = ['identity', 'scope', 'evidence', 'handoff'];
  const $ = (id) => document.getElementById(id);
  const state = { title: '', owner: 'AJH', identity: '', scope: '', evidence: '', handoff: '', checks: {}, history: [], views: 0, stamped: 0 };
  function load() { try { Object.assign(state, JSON.parse(localStorage.getItem(KEY) || '{}')); } catch (_) {} if (!state.checks || typeof state.checks !== 'object') state.checks = {}; if (!Array.isArray(state.history)) state.history = []; }
  function save() { try { localStorage.setItem(KEY, JSON.stringify(state)); } catch (_) {} }
  function completed() { return STEPS.filter((step) => state.checks[step]).length; }
  function summary() { return `AJH Build Passport — ${state.title || 'Untitled build'}\nOwner: ${state.owner || 'AJH'}\nIdentity: ${state.identity || 'Not recorded'}\nScope: ${state.scope || 'Not recorded'}\nEvidence: ${state.evidence || 'Not recorded'}\nHandoff: ${state.handoff || 'Not recorded'}\nChecks: ${completed()}/4`; }
  function escapeHTML(value) { return String(value || '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
  function renderHistory() { const list = $('passport-history-list'); if (!list) return; list.innerHTML = state.history.length ? state.history.slice(0, 8).map((item) => `<div class="passport-history-item"><strong>${escapeHTML(item.title)}</strong><span>${escapeHTML(item.owner)} · ${escapeHTML(item.date)}</span><p>${escapeHTML(item.handoff || item.evidence || 'Evidence stamped.')}</p></div>`).join('') : '<p class="passport-empty">No passports stamped yet. Complete the checks and make the evidence portable.</p>'; }
  function render() {
    [['title', 'title'], ['owner', 'owner'], ['identity', 'identity'], ['scope', 'scope'], ['evidence', 'evidence'], ['handoff', 'handoff']].forEach(([field, id]) => { const el = $('passport-' + id); if (el && document.activeElement !== el) el.value = state[field] || ''; });
    document.querySelectorAll('[data-passport-step]').forEach((input) => { input.checked = Boolean(state.checks[input.dataset.passportStep]); input.closest('.passport-check')?.classList.toggle('is-complete', input.checked); });
    const count = completed(); const ready = count === STEPS.length && state.title.trim();
    $('passport-progress').textContent = `${count}/4`; $('passport-progress-bar').style.width = `${count * 25}%`; $('passport-count').textContent = `${count} of 4 checks complete`; $('passport-stamped').textContent = `${state.stamped} stamped`; $('passport-views').textContent = `${state.views} opened`; $('passport-status').textContent = ready ? 'Ready to stamp' : count ? 'Passport in progress' : 'Awaiting a build'; $('passport-message').textContent = ready ? 'The identity, scope, evidence, and handoff are legible enough to carry forward.' : `${4 - count} check${count === 3 ? '' : 's'} left before this build can cross the line cleanly.`; $('passport-status-pill').textContent = ready ? 'Ready' : 'Local draft'; $('passport-status-card').classList.toggle('is-complete', Boolean(ready)); $('passport-status-card').classList.toggle('is-active', count > 0 && !ready); renderHistory();
  }
  function update(field, value) { state[field] = value; save(); render(); }
  function importDock() { const data = window.ajhDock?.state?.(); if (!data) return; const flight = data.flight || {}; state.title = flight.title || 'Build Dock snapshot'; state.owner = 'AJH'; state.identity = data.sources?.find((row) => row.ready)?.text || 'Imported from Build Dock'; state.scope = data.next || 'Align the latest signals and keep the next move small.'; state.evidence = `Dock signals ready: ${data.sources?.filter((row) => row.ready).length || 0}/4`; state.handoff = data.note || 'Carry the dock snapshot into the next build.'; state.checks = { identity: Boolean(state.identity), scope: Boolean(state.scope), evidence: Boolean(state.evidence), handoff: Boolean(state.handoff) }; save(); render(); open(); }
  function importLighthouse() { const data = window.ajhLighthouse?.state?.(); if (!data) return; state.evidence = `Lighthouse score ${data.score ?? 'ready'} · ${data.report?.filter((item) => item.passed).length || 0} checks passed`; state.checks.evidence = true; save(); render(); open(); }
  function reset() { state.title = ''; state.owner = 'AJH'; state.identity = ''; state.scope = ''; state.evidence = ''; state.handoff = ''; state.checks = {}; save(); render(); }
  function stamp() { if (completed() !== 4 || !state.title.trim()) { $('passport-message').textContent = 'Add a build identity and complete all four checks before stamping.'; $('passport-title').focus(); return; } const item = { title: state.title.trim(), owner: state.owner.trim() || 'AJH', identity: state.identity.trim(), scope: state.scope.trim(), evidence: state.evidence.trim(), handoff: state.handoff.trim(), date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) }; state.history = [item, ...state.history.filter((entry) => entry.title !== item.title)].slice(0, 8); state.stamped += 1; state.checks = {}; state.title = ''; state.identity = ''; state.scope = ''; state.evidence = ''; state.handoff = ''; save(); render(); $('passport-status').textContent = 'Stamped'; $('passport-message').textContent = 'The evidence is logged locally. Future-you has something portable to start from.'; }
  function copy() { if (navigator.clipboard?.writeText) navigator.clipboard.writeText(summary()).then(() => { $('passport-copy').innerHTML = '<i class="fas fa-check"></i> Copied'; setTimeout(() => { $('passport-copy').innerHTML = '<i class="fas fa-share-nodes"></i> Copy passport'; }, 1400); }); }
  function exportJSON() { const url = URL.createObjectURL(new Blob([JSON.stringify({ ...state, exportedAt: new Date().toISOString() }, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `ajh-build-passport-${new Date().toISOString().slice(0, 10)}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function open() { $('passport')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); state.views += 1; save(); render(); }
  function boot() { load(); [['title', 'title'], ['owner', 'owner'], ['identity', 'identity'], ['scope', 'scope'], ['evidence', 'evidence'], ['handoff', 'handoff']].forEach(([field, id]) => $('passport-' + id)?.addEventListener('input', (event) => update(field, event.target.value))); document.querySelectorAll('[data-passport-step]').forEach((input) => input.addEventListener('change', (event) => { state.checks[event.target.dataset.passportStep] = event.target.checked; save(); render(); })); $('passport-import-dock')?.addEventListener('click', importDock); $('passport-import-lighthouse')?.addEventListener('click', importLighthouse); $('passport-reset')?.addEventListener('click', reset); $('passport-copy')?.addEventListener('click', copy); $('passport-export')?.addEventListener('click', exportJSON); $('passport-stamp')?.addEventListener('click', stamp); $('passport-hero-btn')?.addEventListener('click', open); document.addEventListener('keydown', (event) => { if (event.target.matches('input, textarea, select, button, a')) return; if (event.shiftKey && event.key.toLowerCase() === 'b') open(); }); window.ajhPassport = { open, importDock, importLighthouse, stamp, copy, exportJSON, state: () => ({ ...state, checks: { ...state.checks }, history: [...state.history] }) }; render(); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot();
})();
