(function () {
  'use strict';
  const KEY = 'ajh_ship_v1';
  const STEPS = ['packet', 'preview', 'handoff'];
  const FIELDS = ['title', 'owner', 'packet', 'preview', 'evidence', 'handoff'];
  const $ = (id) => document.getElementById(id);
  const state = { draft: {}, checks: {}, history: [], views: 0, ships: 0 };
  function safe(fn, fallback) { try { return fn(); } catch (_) { return fallback; } }
  function load() { Object.assign(state, safe(() => JSON.parse(localStorage.getItem(KEY) || '{}'), {})); state.draft ||= {}; state.checks ||= {}; state.history ||= []; state.views ||= 0; state.ships ||= 0; }
  function save() { safe(() => localStorage.setItem(KEY, JSON.stringify(state)), null); }
  function getDraft() { FIELDS.forEach((name) => { const el = $('ship-' + name); if (el) state.draft[name] = el.value; }); }
  function setDraft() { FIELDS.forEach((name) => { const el = $('ship-' + name); if (el) el.value = state.draft[name] || ''; }); }
  function complete() { return STEPS.filter((step) => state.checks[step]).length; }
  function escapeHTML(value) { return String(value || '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char])); }
  function renderHistory() { const list = $('ship-history-list'); if (!list) return; list.innerHTML = state.history.length ? state.history.slice(0, 8).map((item) => `<div class="ship-history-item"><strong>${escapeHTML(item.title)}</strong><span>${escapeHTML(item.preview)}</span><span>${escapeHTML(item.date)}</span></div>`).join('') : '<span class="ship-card-label">No ships recorded yet. Package the first verified result.</span>'; }
  function render() { getDraft(); const count = complete(); const ready = count === STEPS.length && state.draft.title?.trim(); $('ship-progress').textContent = `${count}/3`; $('ship-count').textContent = `${count} of 3 checks complete`; $('ship-progress-bar').style.width = `${count / 3 * 100}%`; $('ship-status').textContent = ready ? 'Ready to ship' : count ? 'Delivery taking shape' : 'Awaiting a ship packet'; $('ship-message').textContent = ready ? 'The verified result has a preview, evidence, and a clean next-build handoff.' : `${3 - count} check${3 - count === 1 ? '' : 's'} left before this slice is ready to ship.`; $('ship-status-pill').textContent = ready ? 'Ready' : 'Local draft'; $('ship-status-card').classList.toggle('is-complete', Boolean(ready)); $('ship-ships').textContent = state.ships; $('ship-views').textContent = state.views; document.querySelectorAll('[data-ship-step]').forEach((input) => { input.checked = Boolean(state.checks[input.dataset.shipStep]); input.closest('.ship-check')?.classList.toggle('is-complete', input.checked); }); renderHistory(); save(); }
  function importVerify() { const verify = window.ajhVerify?.state?.() || {}; const packet = verify.last || verify; const repair = packet.repair; const proof = packet.proof; const lighthouse = packet.lighthouse; state.draft = { title: `Ship: ${proof?.title || repair?.title || 'Verified result'}`, owner: 'AJH', packet: [repair?.patch && `Patch: ${repair.patch}`, proof?.result && `Result: ${proof.result}`, proof?.behavior && `Behavior: ${proof.behavior}`, lighthouse?.score != null && `Quality: ${lighthouse.score}/100`].filter(Boolean).join(' · ') || 'Import Build Verify after a fresh packet is available.', preview: 'Open the local preview and confirm the changed behavior is visible and usable.', evidence: lighthouse ? `Build Lighthouse ${lighthouse.score}/100 · ${lighthouse.passed} passed · ${lighthouse.warnings} warnings` : 'Name the local audit, test, or observation that travels with this result.', handoff: proof?.record || repair?.notes || 'Leave tomorrow one small next move and the evidence it should inspect.' }; state.checks = { packet: Boolean(state.draft.packet), preview: false, handoff: Boolean(state.draft.handoff) }; setDraft(); render(); $('ship-message').textContent = 'Verify imported. Confirm the preview, name the evidence, then record the ship.'; $('ship')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  function reset() { state.draft = {}; state.checks = {}; setDraft(); render(); }
  function summary() { getDraft(); return `AJH Build Ship — ${state.draft.title || 'Untitled ship'}\nOwner: ${state.draft.owner || 'AJH'}\nVerify packet: ${state.draft.packet || 'Not recorded'}\nPreview: ${state.draft.preview || 'Not recorded'}\nEvidence: ${state.draft.evidence || 'Not recorded'}\nHandoff: ${state.draft.handoff || 'Not recorded'}\nChecks: ${complete()}/3`; }
  function copy() { const done = () => { const button = $('ship-copy'); button.innerHTML = '<i class="fas fa-check"></i> Copied ship'; setTimeout(() => { button.innerHTML = '<i class="fas fa-share-nodes"></i> Copy ship'; }, 1400); }; const text = summary(); if (navigator.clipboard?.writeText) navigator.clipboard.writeText(text).then(done).catch(() => fallbackCopy(text, done)); else fallbackCopy(text, done); }
  function fallbackCopy(text, done) { const area = document.createElement('textarea'); area.value = text; area.style.position = 'fixed'; area.style.opacity = '0'; document.body.append(area); area.select(); safe(() => document.execCommand('copy'), null); area.remove(); done(); }
  function exportJSON() { getDraft(); const url = URL.createObjectURL(new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), ...state }, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `ajh-build-ship-${new Date().toISOString().slice(0, 10)}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 800); }
  function record() { render(); if (complete() !== STEPS.length || !state.draft.title?.trim()) { $('ship-message').textContent = 'Add a ship title and complete all three checks before recording.'; $('ship-title')?.focus(); return; } const item = { ...state.draft, date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) }; state.history.unshift(item); state.history = state.history.slice(0, 12); state.ships += 1; state.draft = {}; state.checks = {}; setDraft(); render(); $('ship-status').textContent = 'Ship recorded'; $('ship-message').textContent = 'The verified result is packaged locally. Tomorrow can start from the handoff instead of reconstructing it.'; }
  function open() { $('ship')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); state.views += 1; save(); render(); }
  function boot() { if (!$('ship')) return; load(); state.views += 1; setDraft(); FIELDS.forEach((name) => $('ship-' + name)?.addEventListener('input', render)); document.querySelectorAll('[data-ship-step]').forEach((input) => input.addEventListener('change', (event) => { state.checks[event.target.dataset.shipStep] = event.target.checked; render(); })); $('ship-import')?.addEventListener('click', importVerify); $('ship-reset')?.addEventListener('click', reset); $('ship-copy')?.addEventListener('click', copy); $('ship-export')?.addEventListener('click', exportJSON); $('ship-record')?.addEventListener('click', record); $('ship-hero-btn')?.addEventListener('click', open); document.addEventListener('keydown', (event) => { if (event.target.matches('input, textarea, select, button, a')) return; if (event.shiftKey && event.key.toLowerCase() === 'q') open(); }); window.ajhShip = { open, importVerify, reset, copy, exportJSON, record, state: () => ({ ...state, draft: { ...state.draft }, checks: { ...state.checks }, history: [...state.history] }) }; render(); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot();
})();
